# Site settings
title: Margo Kulkarni
email: margo.r.kulkarni@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey! I'm Margo Kulkarni and I'm a Data Scientist in Berlin.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://margorkulkarni.com" # the base hostname & protocol for your site
twitter_username: m_rgoK
github_username:  margo-K

# Build settings
markdown: kramdown
